# Base configs
baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photos by Nathan Stavridis"
subtitle: "I take pictures."
author: "Nathan Stavridis"
header:
 title: "Photography"
 subtitle: "by Nathan Stavridis"
footer:
 name: "Hey there, my name is Nathan"
 bio: "I'm own cameras, lenses, and I enjoy seeing the world through them."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks

